---
notifications:
- ethenry@ucsc.edu
name: Shakespeare Santa Cruz Records
status: New
type: ingest
file_prefix: ua0041/
work_type: Work
file_method: remove-and-add
visibility: restricted
ignored_columns: []
shakespeare-santa-cruz-records_2: shakespeare-santa-cruz-records_2
ingest: ingest
OK: OK
