---
notifications:
- ethenry@ucsc.edu
name: DeCoup Ingest
status: New
type: Update / Edit / Overlay
file_prefix: ms0038_decou/
work_type: Work
file_method: remove-and-add
visibility: restricted
ignored_columns: []
decoup-ingest: decoup-ingest
OK: OK
