---
notifications:
- ethenry@ucsc.edu
name: Santa Cruz County historic photograph collection - Simple images
status: New
type: ingest
file_prefix: ms0427/
work_type: Work
file_method: remove-and-add
visibility: restricted
ignored_columns: []
santa-cruz-county-historic-photograph-collection-simple-images: santa-cruz-county-historic-photograph-collection-simple-images
ingest: ingest
OK: OK
