---
notifications:
- ethenry@ucsc.edu
name: Porter College Ingest
status: New
type: ingest
file_prefix: ua0133/
complex_objects: ''
work_type: Work
file_method: remove-and-add
visibility: restricted
ignored_columns: []
porter-college-ingest: porter-college-ingest
ingest: ingest
OK: OK
