---
notifications:
- ethenry@ucsc.edu
name: UA50 test staging 2
status: New
type: ingest
file_prefix: ua0050/
work_type: Work
file_method: remove-and-add
visibility: restricted
ignored_columns: []
ua50-test-staging-2: ua50-test-staging-2
ingest: ingest
OK: OK
