---
notifications:
- ethenry@ucsc.edu
name: RMB makeup ingest staging test
status: New
type: ingest
file_prefix: ms0020_ingest3/
work_type: Work
file_method: remove-and-add
visibility: restricted
ignored_columns: []
rmb-makeup-ingest-staging-test: rmb-makeup-ingest-staging-test
ingest: ingest
OK: OK
