---
notifications:
- ethenry@ucsc.edu
name: UA50 Test
status: New
type: ingest
file_prefix: ua0050/
work_type: Work
file_method: remove-and-add
visibility: open
ignored_columns: []
ua50-test: ua50-test
ingest: ingest
OK: OK
