---
notifications:
- ethenry@ucsc.edu
name: Demo Operation
status: New
type: ingest
file_prefix: ''
work_type: Work
file_method: remove-and-add
visibility: restricted
ignored_columns: []
demo-operation: demo-operation
ingest: ingest
OK: OK
