---
notifications:
- ethenry@ucsc.edu
name: another test op
status: New
type: ingest
file_prefix: Cats/
work_type: Work
file_method: remove-and-add
visibility: restricted
ignored_columns: []
another-test-op: another-test-op
ingest: ingest
OK: OK
