---
notifications:
- ethenry@ucsc.edu
name: Porter College Scrapbook Ingest
status: New
type: ingest
file_prefix: ua0133/
work_type: Work
file_method: remove-and-add
visibility: restricted
ignored_columns: []
porter-college-scrapbook-ingest: porter-college-scrapbook-ingest
ingest: ingest
OK: OK
