---
notifications:
- ethenry@ucsc.edu
name: Lick Complex
status: New
type: Update / Edit / Overlay
file_prefix: ua0036/
work_type: Work
file_method: remove-and-add
visibility: restricted
ignored_columns: []
lick-complex: lick-complex
OK: OK
