---
notifications:
- ethenry@ucsc.edu
name: UA-50 Test Staging
status: New
type: ingest
file_prefix: ua0050/
work_type: Work
file_method: remove-and-add
visibility: restricted
ignored_columns: []
ua-50-test-staging: ua-50-test-staging
ingest: ingest
OK: OK
