---
notifications:
- ethenry@ucsc.edu
name: Ansel Adams Photographs
status: New
type: Update / Edit / Overlay
file_prefix: ms0020/
work_type: Work
file_method: remove-and-add
visibility: restricted
ignored_columns: []
ansel-adams-photographs: ansel-adams-photographs
OK: OK
