---
notifications:
- ethenry@ucsc.edu
name: UA50 Complex Test Staging 2
status: New
type: ingest
file_prefix: ''
work_type: Work
file_method: remove-and-add
visibility: restricted
ignored_columns: []
ua50-complex-test-staging-2: ua50-complex-test-staging-2
ingest: ingest
OK: OK
