---
notifications:
- ethenry@ucsc.edu
name: Combined Campus History
status: New
type: Update / Edit / Overlay
file_prefix: Combined_Campus_History
work_type: Work
file_method: remove-and-add
visibility: restricted
ignored_columns: []
combined-campus-history: combined-campus-history
OK: OK
