---
notifications:
- ethenry@ucsc.edu
name: MS20_Berryessa_remodel
status: New
type: ingest
file_prefix: ms0020_done/
work_type: Work
file_method: remove-and-add
visibility: restricted
ignored_columns: []
ms20_berryessa_remodel: ms20_berryessa_remodel
ingest: ingest
OK: OK
