---
notifications:
- ethenry@ucsc.edu
name: A test cat ingest
status: New
type: ingest
file_prefix: Cats/
work_type: Work
file_method: remove-and-add
visibility: restricted
ignored_columns: []
a-test-cat-ingest_1: a-test-cat-ingest_1
ingest: ingest
OK: OK
