---
notifications:
- ethenry@ucsc.edu
name: cmf staging test 2
status: New
type: ingest
file_prefix: ms0414/
work_type: Work
file_method: remove-and-add
visibility: restricted
ignored_columns: []
cmf-staging-test-2: cmf-staging-test-2
ingest: ingest
OK: OK
