---
notifications:
- ethenry@ucsc.edu
name: ms020 remodel - Haight-Ashbury
status: New
type: ingest
file_prefix: ''
work_type: Work
update_identifier: masterFilename
file_method: remove-and-add
visibility: restricted
ignored_columns: []
ms020-remodel-haight-ashbury: ms020-remodel-haight-ashbury
ingest: ingest
OK: OK
